site_name: Universe and you
nav:
  - Home: 'index.md'
  - Contact: 'contact.md'
  - Resources: 'ressourc.md'

theme: 
  name: readthedocs
  color_mode: light
  nav_style: dark
  locale: en
  analytics: null
  anonymize_ip: true
  logo:

